### PR TITLE
2.3.12

### PR DESCRIPTION
**Pull request by gpgreen**
Adding code drop of version 2.3.12

Fixed some dependencies in pom.xml

### CODE REVIEW

**Comment by Enquier** [comment]
Any reason why we shouldn't just create a releases/2.3.12 branch instead to mirror MDK?

**Comment by gpgreen** [comment]
In most projects i've worked on there is a branch corresponding with the release, with tags specifying minor releases. So in this case, wouldn't we have a 2.3 branch and tags specifying .1,.2,.3 etc?

If you have a branch for every minor version, that means your going to have a lot of static branches.

**Comment by Enquier** [comment]
That works for me, I guess I just want to make sure we are using a consistent style for the version releases.

**Comment by gpgreen** [comment]
Right now there are only 4 branches in the EMS-Repo project. If you want to create more and have me do a pull request against that, then let me know.

**Comment by Enquier** [comment]
I think we can work out the branch question as we go along. I just wanted to bring it up as a topic for conversation. Seems like you and I are the only ones that care. I assume you got this dump from the team directly, and baring any input from them lets just merge this and call it a day

**Pull request merged**
